

try:

    print(num)
except NameError:  # 捕获 NameError 异常
    print('有错误')
